---

version: '3.9'

services:
  app:
    image: node:lts-alpine
    container_name: ${APP_NAME}_app
    restart: on-failure
    networks:
      - default
      - shared
    volumes:
      - ./app:/app:rw,cached
      - ./.env:/app/.env
    working_dir: /app
    command: "yarn dev"
    labels:
      - traefik.enable=true
      - traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${PROJECT_SERVICES_NAMESPACE}.docker`)
      - traefik.http.routers.${APP_NAME}.entrypoints=websecure
      - traefik.http.services.${APP_NAME}.loadbalancer.server.port=3000
      - traefik.http.routers.${APP_NAME}.tls=true

networks:
  shared:
    external: true
    name: ${SHARED_SERVICES_NETWORK}

...
