---

name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  integration:
    name: Node ${{ matrix.node }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-22.04"]
        node: ["18"]
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Load cached frontend dependencies
        id: cached-yarn-dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install frontend dependencies
        if: steps.cached-yarn-dependencies.outputs.cache-hit != 'true'
        run: yarn install

      - name: Mix frontend code
        run: yarn run build

      - if: github.event_name == 'pull_request'
        name: Validate all commits from PR
        uses: wagoid/commitlint-github-action@v5
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules

      - name: Linting
        run: yarn run lint

      - name: Type checking
        run: yarn run check-types

      - name: Run unit tests
        run: yarn run test

      - name: Run e2e tests
        run: yarn run e2e:headless

...
